// Todo-Angular/todo-app/src/app/todo-item/todo-item.component.ts
import { Component,  Input } from '@angular/core';
import { TodoService } from '../shared/todo-storage.service';
import { Todo } from '../shared/todo';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItemComponent  {
  @Input() todo: Todo;

  constructor(private todoService: TodoService) { }

  onDeleteTodo() {
      console.log(this.todo);
      this
      .todoService
      .delTodo(this.todo.id).subscribe();
  }

}

<div class="container">

  <input
  [disabled]="true"
  type="text"
  placeholder="Enter Todo"
  class="todo--input"
  [(ngModel)]="todo.text"/>

  <button
  type="button"
  class="btn delete"
  (click)="onDeleteTodo()">Delete</button>

</div>

// Todo-ReactJS/todo-app/src/todo-item/todo-item.js
import React from 'react'
import './todo-item.css'

const todoItem = (props) => {
    return (
        <div className="container">
            <input
                type="text"
                className="todo--input"
                value={props.value}
                disabled={true} />

            <button
                type="button"
                className="btn delete"
                onClick={props.deleteTodo}
            >Delete
            </button>

        </div>
    )
}
export default todoItem;
