// Todo-ReactJS/todo-app/src/App.js
import React, { Component } from 'react';
import './App.css';
import TodoInput from './todo-input/todo-input'
import TodoList from './todo-list/todo-list'

class App extends Component {
  state = {
    todos: [],
    todo_input: {
      btn_disabled: true,
      input_text: ''
    }
  }
  onSaveTodo = () => {
    const current_text = this.state.todo_input.input_text
    let prev_todo = [...this.state.todos]
    prev_todo.push(current_text)
    this.setState({
      todos: prev_todo
    })
  }
  onInputChanged = (event) => {
    const current_text = event.target.value
    if (current_text === '') {
      const cur_input = {
        btn_disabled: true,
        input_text: event.target.value
      }
      this.setState({
        todo_input: cur_input
      })
    } else {
      const cur_input = {
        btn_disabled: false,
        input_text: event.target.value
      }
      this.setState({
        todo_input: cur_input
      })
    }
  }
  onDeleteTodo = (key) => {
    let prev_todo = [...this.state.todos]
    prev_todo.splice(key, 1);
    this.setState({
      todos: prev_todo
    })
  }
  render() {

    return (
      <div className="App">
        <div className="container--todo-header">
          <h1>Todo App ReactJS</h1>
        </div>
        <TodoInput
          disabled={this.state.todo_input.btn_disabled}
          clicked={this.onSaveTodo}
          changed={this.onInputChanged} />
        <hr></hr>
        <TodoList todos={this.state.todos}  delete={this.onDeleteTodo}></TodoList>
      </div>
    );
  }
}

export default App;

// Todo-VueJS/todo-app/src/App.vue
<template>
  <div id="app">
    <div class="container--todo-header">
      <h1>Todo App VueJS</h1>
    </div>
    <todoInput @onTodoAdd = "handleTodoAdd"></todoInput>
    <hr/>
    <TodoList :todos="todos"
      @onDeleteTodo="handleDeleteTodo"></TodoList>

    <!-- <div v-for="(todo,index) in todos"
    :key="index"
    class="margin-top-50">
      <todoList
      @onDeleteTodo = "handleDeleteTodo"
      :todoEl="todo"
      :todoInd="index"></todoList>
    </div> -->
  </div>
</template>

<script>
import todoInput from './components/todo-input/todo-input'
import TodoList from './components/todo-list/todo-list.vue'
export default {
  name: 'App',
  data() {
    return {
      todos: []
    }
  },
  methods: {
    handleTodoAdd(todo) {
      this.todos.push(todo)
    },
    handleDeleteTodo(ind) {
      this
      .todos
      .splice(ind,1)
    }
  },
  components: {
    todoInput,
    TodoList
  }
}
</script>

<style>
.container--todo-header {
  display: flex;
  justify-content: center;
}
.margin-top-50 {
  margin-top: 50px;
}
</style>
